export const skillsData = {
  backend: [
    { name: 'C#.NET', percentage: 90 },
    { name: 'ASP.NET Core', percentage: 90 },
    { name: '.NET Core', percentage: 90 },
    { name: 'Web API', percentage: 90 },
    { name: 'ASP.NET MVC', percentage: 90 },
    { name: 'Microservices', percentage: 90 },
    { name: 'Ocelot', percentage: 85 },
    { name: 'JWT Token', percentage: 90 },
    { name: 'SignalR', percentage: 90 },
    { name: 'Swagger', percentage: 90 },
    { name: 'Azure Functions', percentage: 85 },
    { name: 'Azure Service Bus', percentage: 85 },
    { name: 'RabbitMQ', percentage: 80 },
    { name: 'Apache Kafka', percentage: 80 },
    { name: 'Redis', percentage: 90 },
    { name: 'LINQ', percentage: 90 },
    { name: 'Entity Framework', percentage: 90 },
  ],
  frontend: [
    { name: 'ReactJs', percentage: 90 },
    { name: 'Angular', percentage: 90 },
    { name: 'TypeScript', percentage: 90 },
    { name: 'JavaScript', percentage: 90 },
    { name: 'AngularJS', percentage: 80 },
    { name: 'jQuery', percentage: 85 },
    { name: 'AJAX', percentage: 90 },
    { name: 'Redux', percentage: 90 },
    { name: 'NgRx', percentage: 90 },
    { name: 'RxJS', percentage: 90 },
    { name: 'Material UI', percentage: 90 },
    { name: 'Bootstrap 5', percentage: 90 },
    { name: 'HTML5', percentage: 90 },
    { name: 'CSS3', percentage: 90 },
    { name: 'SASS', percentage: 90 },
    { name: 'LESS', percentage: 85 },
    { name: 'SCSS', percentage: 90 },
    { name: 'Tailwind CSS', percentage: 90 },
  ],
  database: [
    { name: 'MS SQL Server', percentage: 90 },
    { name: 'ORACLE 11g', percentage: 85 },
    { name: 'MySQL', percentage: 90 },
    { name: 'SQLite', percentage: 80 },
    { name: 'PostgreSQL', percentage: 85 },
    { name: 'MongoDB', percentage: 90 },
    { name: 'DynamoDB', percentage: 85 },
    { name: 'Azure Cosmos DB', percentage: 85 },
    { name: 'Azure SQL Database', percentage: 90 },
  ],
  devops: [
    { name: 'Azure', percentage: 90 },
    { name: 'Docker', percentage: 90 },
    { name: 'Azure DevOps', percentage: 90 },
    { name: 'Jenkins', percentage: 85 },
    { name: 'Docker Hub', percentage: 90 },
    { name: 'Docker Compose', percentage: 90 },
    { name: 'Kubernetes', percentage: 85 },
    { name: 'Minikube', percentage: 80 },
    { name: 'MicroK8s', percentage: 80 },
  ],
  sourceControl: [
    { name: 'Azure DevOps', percentage: 90 },
    { name: 'GitHub', percentage: 90 },
    { name: 'Git', percentage: 90 },
    { name: 'GitLab', percentage: 90 },
    { name: 'Bitbucket', percentage: 85 },
    { name: 'SVN', percentage: 80 },
    { name: 'TFS', percentage: 80 },
    { name: 'SourceTree', percentage: 90 },
  ],
};