export const skillsData = {
  backend: [
    { name: 'C#.NET (.NET 9/10)', percentage: 90 },
    { name: 'ASP.NET Core', percentage: 90 },
    { name: '.NET Core', percentage: 90 },
    { name: 'Web API', percentage: 90 },
    { name: 'ASP.NET MVC', percentage: 90 },
    { name: 'Microservices', percentage: 90 },
    { name: 'Minimal APIs', percentage: 85 },
    { name: 'Ocelot', percentage: 85 },
    { name: 'YARP', percentage: 80 },
    { name: 'gRPC', percentage: 80 },
    { name: 'JWT Token', percentage: 90 },
    { name: 'OAuth2 / OpenID Connect', percentage: 85 },
    { name: 'IdentityServer', percentage: 80 },
    { name: 'SignalR', percentage: 90 },
    { name: 'Swagger', percentage: 90 },
    { name: 'Azure Functions', percentage: 85 },
    { name: 'Azure Service Bus', percentage: 85 },
    { name: 'RabbitMQ', percentage: 80 },
    { name: 'MassTransit', percentage: 80 },
    { name: 'Apache Kafka', percentage: 80 },
    { name: 'Polly', percentage: 80 },
    { name: 'Hangfire', percentage: 85 },
    { name: 'Redis', percentage: 90 },
    { name: 'LINQ', percentage: 90 },
    { name: 'Entity Framework Core', percentage: 90 },
    { name: 'Dapper', percentage: 85 },
  ],
  architecture: [
    { name: 'Clean Architecture', percentage: 90 },
    { name: 'CQRS', percentage: 85 },
    { name: 'MediatR', percentage: 85 },
    { name: 'Domain-Driven Design', percentage: 85 },
    { name: 'Repository Pattern', percentage: 90 },
    { name: 'SOLID Principles', percentage: 90 },
    { name: 'Event-Driven Messaging', percentage: 85 },
    { name: 'Resilience Patterns (Retry, Circuit Breaker)', percentage: 80 },
    { name: 'Outbox Pattern', percentage: 80 },
  ],
  frontend: [
    { name: 'ReactJs', percentage: 90 },
    { name: 'Angular', percentage: 90 },
    { name: 'TypeScript', percentage: 90 },
    { name: 'JavaScript', percentage: 90 },
    { name: 'AngularJS', percentage: 80 },
    { name: 'jQuery', percentage: 85 },
    { name: 'AJAX', percentage: 90 },
    { name: 'Redux', percentage: 90 },
    { name: 'NgRx', percentage: 90 },
    { name: 'RxJS', percentage: 90 },
    { name: 'Material UI', percentage: 90 },
    { name: 'Bootstrap 5', percentage: 90 },
    { name: 'HTML5', percentage: 90 },
    { name: 'CSS3', percentage: 90 },
    { name: 'SASS', percentage: 90 },
    { name: 'LESS', percentage: 85 },
    { name: 'SCSS', percentage: 90 },
    { name: 'Tailwind CSS', percentage: 90 },
  ],
  database: [
    { name: 'MS SQL Server', percentage: 90 },
    { name: 'Azure SQL Database', percentage: 90 },
    { name: 'ORACLE 11g', percentage: 85 },
    { name: 'MySQL', percentage: 90 },
    { name: 'SQLite', percentage: 80 },
    { name: 'PostgreSQL', percentage: 85 },
    { name: 'MongoDB', percentage: 90 },
    { name: 'DynamoDB', percentage: 85 },
    { name: 'Azure Cosmos DB', percentage: 85 },
    { name: 'Stored Procedures', percentage: 85 },
  ],
  devops: [
    { name: 'Azure', percentage: 90 },
    { name: 'Docker', percentage: 90 },
    { name: 'Azure DevOps CI/CD', percentage: 90 },
    { name: 'Jenkins', percentage: 85 },
    { name: 'Docker Hub', percentage: 90 },
    { name: 'Docker Compose', percentage: 90 },
    { name: 'Kubernetes', percentage: 85 },
    { name: 'Minikube', percentage: 80 },
    { name: 'MicroK8s', percentage: 80 },
    { name: 'Azure Blob Storage', percentage: 85 },
  ],
  testing: [
    { name: 'xUnit', percentage: 85 },
    { name: 'NUnit', percentage: 85 },
    { name: 'Postman', percentage: 90 },
    { name: 'Integration Testing', percentage: 85 },
    { name: 'Serilog', percentage: 85 },
    { name: 'NLog', percentage: 80 },
    { name: 'Application Insights', percentage: 85 },
    { name: 'OpenTelemetry', percentage: 80 },
    { name: 'Elastic / Kibana', percentage: 75 },
  ],
  sourceControl: [
    { name: 'Azure DevOps', percentage: 90 },
    { name: 'GitHub', percentage: 90 },
    { name: 'Git', percentage: 90 },
    { name: 'GitLab', percentage: 90 },
    { name: 'Bitbucket', percentage: 85 },
    { name: 'SVN', percentage: 80 },
    { name: 'TFS', percentage: 80 },
    { name: 'SourceTree', percentage: 90 },
  ],
  tooling: [
    { name: 'Visual Studio', percentage: 90 },
    { name: 'Visual Studio Code', percentage: 90 },
    { name: 'Python', percentage: 80 },
    { name: 'FastAPI', percentage: 80 },
    { name: 'Claude', percentage: 85 },
    { name: 'GitHub Copilot', percentage: 85 },
    { name: 'Gemini', percentage: 80 },
    { name: 'ChatGPT', percentage: 80 },
  ],
};
