/* ================= DOMAINS ================= */
export const DOMAINS = [
  { id: 'acquire', label: '1 · Acquire', color: 'var(--c-acquire)' },
  { id: 'know', label: '2 · Know', color: 'var(--c-know)' },
  { id: 'originate', label: '3 · Sell / Originate', color: 'var(--c-sell)' },
  { id: 'assess', label: '4 · Assess / Decide', color: 'var(--c-assess)' },
  { id: 'fulfill', label: '5 · Fulfill / Fund', color: 'var(--c-fund)' },
  { id: 'use', label: '6 · Use / Service', color: 'var(--c-use)' },
  { id: 'control', label: '7 · Control', color: 'var(--c-control)' },
  { id: 'close', label: '8 · Settle / Close', color: 'var(--c-close)' },
];
export const DOMAIN_COLOR = {};
DOMAINS.forEach((d) => { DOMAIN_COLOR[d.id] = d.color; });
export const DOMAIN_LABEL_SHORT = { acquire: 'Acquire', know: 'Know', originate: 'Originate', assess: 'Assess', fulfill: 'Fulfill', use: 'Use', control: 'Control', close: 'Close' };

/* ================= STAGES (32) ================= */
export const STAGES = [
  { title: "Customer Need", domain: "acquire", dept: "customer",
    desc: "A person has a financial need — somewhere to keep a salary, a home, a car, working capital, or a way to save.", modules: [] },
  { title: "Acquisition", domain: "acquire", dept: "sales",
    desc: "The prospect reaches BRAC Bank through a branch officer, RM, digital channel, or partner campaign. The lead is captured.", modules: [] },
  { title: "Identity", domain: "know", dept: "sales",
    desc: "NID capture and live face verification establish who the applicant actually is — captured at the point of contact by Sales/RM or the digital channel.", modules: ["ekyc"] },
  { title: "eKYC / CDD", domain: "know", dept: "riskcompliance",
    desc: "Customer due diligence builds the compliance profile — occupation, source of funds, and risk category — under compliance ownership.", modules: ["kyc"] },
  { title: "AML / Sanctions Screening", domain: "know", dept: "sanction",
    desc: "Sanctions and financial-crime screening clear the customer before any account or facility can be created. A Clear result proceeds immediately; an Exception is routed to Compliance Review before identity can be finalized.", modules: ["aml"] },
  { title: "CIF Establishment", domain: "know", dept: "los",
    desc: "One Customer Information File is created in the LOS/core platform. Every product attaches to this single customer relationship.", modules: ["cif"] },
  { title: "Product Selection", domain: "originate", dept: "sales",
    desc: "The customer's need is routed into one of three journeys, each carrying its own rules, documents, and pace.", modules: ["casa", "dps", "fdr", "loanorig", "cards"],
    branches: { sync: true, tracks: [
      { name: "Deposit", color: "var(--c-sell)", items: ["Savings / Current", "DPS", "FDR"] },
      { name: "Loan", color: "var(--c-fund)", items: ["Personal", "Auto", "Home", "Digital", "Cash-Secured"] },
      { name: "Card", color: "var(--c-know)", items: ["Debit", "Credit"] },
    ] } },
  { title: "Eligibility Check", domain: "originate", dept: "los",
    desc: "Before an application is even created, the system checks age, income, employment, existing relationship, and product policy for a basic eligibility gate.", modules: ["loanorig"] },
  { title: "Application Origination", domain: "originate", dept: "sales",
    desc: "Sales/RM or the digital channel captures the applicant's personal, business, and property information into a draft application.", modules: ["loanorig"] },
  { title: "Application Parking", domain: "originate", dept: "los",
    desc: "The submitted application is assigned an Application ID and CIF link, and enters the bank's processing workflow. Parking is not approval.", modules: ["loanorig"] },
  { title: "DRD — Digital Review Desk", domain: "assess", dept: "drd",
    desc: "The digital review desk checks completeness, document validity, and data consistency. It then asks 'Verification Need?' — if yes, it triggers an early CPV pass before deciding Complete / Deficiency / Reject; if no, the file moves straight on. (Loan-path detail — deposit and card paths use a lighter check.)", modules: ["cpv"] },
  { title: "Dedupe / AML / KYC — Application Control Checks", domain: "assess", dept: "dedupe",
    desc: "Dedupe, application-level AML/sanction screening, and a KYC re-check run together as one control-checks gate before the file is allowed into credit assessment.", modules: ["loanorig"] },
  { title: "CIB", domain: "assess", dept: "cib",
    desc: "Pulls the applicant's credit bureau report: existing liabilities, delinquency history, and overall exposure.", modules: ["cib"] },
  { title: "CPV / Verification", domain: "assess", dept: "cpv",
    desc: "Independently verifies residence, employment, business, or income information the applicant declared.", modules: ["cpv"] },
  { title: "Credit Assessment", domain: "assess", dept: "credit",
    desc: "Combines income analysis, liability analysis, and risk analysis into credit scoring / underwriting, producing a lending recommendation for the sanctioning authority.", modules: ["income", "creditassess"] },
  { title: "Credit Decision / Sanction", domain: "assess", dept: "sanctioning",
    desc: "The approving authority signs off — approve, decline, or refer — and sets the approved terms. Sanction is not disbursement.", modules: ["creditdecision"] },
  { title: "Conditions & Guarantor", domain: "fulfill", dept: "fulfillment",
    desc: "Post-approval conditions are worked through — a guarantor is nominated, KYC'd, and accepted where the product requires one.", modules: ["guarantor"] },
  { title: "Acknowledgement & Repayment Account", domain: "fulfill", dept: "fulfillment",
    desc: "The customer formally acknowledges the approved terms, and a CASA account is linked as the source for scheduled EMI collection.", modules: ["repayacct"] },
  { title: "Documentation & Signature", domain: "fulfill", dept: "docsops",
    desc: "Legal loan documents are generated, reviewed, signed, and uploaded — checked for completeness before anything is disbursed.", modules: ["docs"] },
  { title: "Legal / Valuation / Security", domain: "fulfill", dept: "legal",
    desc: "For secured products only — property valuation, title/legal vetting, or vehicle security documentation is completed.", modules: ["docs"] },
  { title: "Final Verification", domain: "fulfill", dept: "docsops",
    desc: "A last check across documents, conditions, and authentication before the file is marked ready for disbursement.", modules: ["docs"] },
  { title: "Booking / Account Creation", domain: "fulfill", dept: "corebanking",
    desc: "The facility is booked — a loan or product account is created and core banking is updated — a distinct moment from disbursement: the account can exist before any money actually moves.", modules: ["corebanking"] },
  { title: "Disbursement", domain: "fulfill", dept: "disbursement",
    desc: "Once every condition, document, and verification is complete, the disbursement instruction is authorized and funds are released — to the customer's account, directly to a vendor/dealer (e.g. an auto loan paid to the dealership), or another approved payee, depending on product policy.", modules: ["disbursement"] },
  { title: "Activation", domain: "use", dept: "corebanking",
    desc: "The product is marked active and the customer can now actually use it — the final handoff from origination into everyday servicing.", modules: ["corebanking"] },
  { title: "Use & Servicing", domain: "use", dept: "servicing",
    desc: "Deposits, withdrawals, transfers, card spend, EMIs, and statements — the daily rhythm of an active banking relationship.", modules: ["payment", "cards", "corebanking"] },
  { title: "Monitoring", domain: "control", dept: "riskcompliance",
    desc: "Three streams run continuously — AML monitoring, credit/portfolio monitoring, and transaction monitoring — feeding one portfolio control view of payment behaviour and risk.", modules: ["reporting"],
    branches: { sync: false, tracks: [
      { name: "Normal path", color: "var(--c-use)", items: ["On-time EMI", "Next cycle"] },
      { name: "Delinquent path", color: "var(--c-control)", items: ["Overdue", "Collection", "Regularize or Escalate"] },
    ] } },
  { title: "Collection", domain: "control", dept: "collection",
    desc: "Overdue accounts are contacted and, where possible, brought back to a payment arrangement.", modules: ["collection"] },
  { title: "Recovery", domain: "control", dept: "recovery",
    desc: "Serious delinquency or default is escalated here — legal, collateral, or restructuring action is managed.", modules: ["recovery"] },
  { title: "Post-Disbursement Review", domain: "control", dept: "postreview",
    desc: "A control layer reviews disbursed files for completeness and compliance exceptions after the fact.", modules: ["reporting"] },
  { title: "Settlement / Maturity", domain: "close", dept: "servicing",
    desc: "Outstanding principal, interest, and fees reach zero through one of three routes, and the facility is fully settled.", modules: ["recovery", "corebanking"],
    branches: { sync: true, tracks: [
      { name: "Normal Maturity", color: "var(--c-use)", items: ["Full Term Completed"] },
      { name: "Early Settlement", color: "var(--c-sell)", items: ["Customer Pays Off Early"] },
      { name: "Recovery Payoff", color: "var(--c-control)", items: ["Collateral / Legal Resolution"] },
    ] } },
  { title: "Closure & Security Release", domain: "close", dept: "docsops",
    desc: "The product closes and any lien or security is released. Closing a loan does not close the customer relationship.", modules: ["corebanking", "reporting"] },
  { title: "Retention & Cross-Sell", domain: "close", dept: "custservice",
    desc: "The relationship continues — a satisfied customer is offered the next product, looping back to Product Selection.", modules: ["custservice"] },
];

/* ================= DEPARTMENTS ================= */
export const DEPT_DOMAINS = DOMAINS;
export const DEPARTMENTS = [
  { id: "customer", code: "DEPT-00", name: "Customer / Applicant", domain: "acquire",
    purpose: "Originates every request the bank processes — the need, the information, the documents, the consent.",
    receives: "—", handsTo: "Sales / RM / Channel",
    human: "Provides information, documents, consent, and acceptance at every stage.", system: "Interacts via branch, app, or web channel.",
    workflow: ["Financial Need Arises", "Reaches Out to a Channel", "Supplies Information & Documents", "Reviews & Accepts Terms", "Uses the Product"] },
  { id: "sales", code: "DEPT-01", name: "Sales / RM / DSE / Channel", domain: "acquire",
    purpose: "Sources the customer, understands the need, recommends a product, and creates the application. Does not approve credit.",
    receives: "Customer", handsTo: "Application / LOS",
    human: "Captures NID, personal, employment, and product-specific data face-to-face or via digital onboarding.", system: "Loan Origination front-end captures and drafts the application.",
    workflow: ["Find Customer", "Understand Need", "Recommend Product", "Collect Information", "Create & Submit Application"] },
  { id: "los", code: "DEPT-02", name: "Application / LOS", domain: "originate",
    purpose: "Stores and orchestrates the application workflow — assigns IDs, tracks status, and routes between departments.",
    receives: "Sales / RM", handsTo: "DRD",
    human: "Ops team monitors queue health and resolves stuck workflow states.", system: "Assigns Application ID, links CIF, tracks status transitions, and routes the file automatically.",
    workflow: ["Application Received", "ID & CIF Link Assigned", "Status Set to Parked", "Routed to DRD"] },
  { id: "drd", code: "DEPT-03", name: "DRD — Digital Review Desk", domain: "assess",
    purpose: "First back-office checkpoint: makes sure a digitally submitted application is actually processable before deeper credit work begins.",
    receives: "Application / LOS", handsTo: "Dedupe",
    human: "Reviewer checks completeness, document validity, and data consistency; coordinates CPV.", system: "Tracks DRD_STATUS: Pending, In Review, Completed, Deficiency, Returned, Rejected.",
    workflow: ["Application Completeness Check", "Document Review", "Data Consistency Check", "CPV Coordination", "Outcome: Complete / Deficiency / Reject"] },
  { id: "dedupe", code: "DEPT-04", name: "Dedupe", domain: "assess",
    purpose: "Determines whether this customer, application, or exposure already exists in the bank's records.",
    receives: "DRD", handsTo: "Sanction / AML Screening",
    human: "Reviews possible-duplicate flags that the system can't resolve automatically.", system: "Matches NID, mobile, CIF, name, and DOB against existing records.",
    workflow: ["Identifying Data Collected", "Match Against NID / CIF / Mobile", "Classify: New / Existing / Possible Duplicate", "Link to Existing CIF if Found"] },
  { id: "sanction", code: "DEPT-05", name: "Sanction / AML Screening", domain: "assess",
    purpose: "A compliance control gate — screens for sanctions and financial-crime matches. Not the same as credit sanction.",
    receives: "Dedupe", handsTo: "CIB",
    human: "Investigates and dispositions any alert the screening engine raises.", system: "Matches customer and transaction data against watchlists.",
    workflow: ["Screen Against Watchlists", "Match Found?", "Investigate Alert", "Clear or Escalate"] },
  { id: "cib", code: "DEPT-06", name: "CIB Team / Credit Bureau Interface", domain: "assess",
    purpose: "Obtains and processes the applicant's credit bureau information.",
    receives: "Sanction Screening", handsTo: "CPV / Verification",
    human: "Interprets bureau flags such as classified accounts per credit policy.", system: "Retrieves the CIB report via the credit bureau interface.",
    workflow: ["CIB Request Sent", "Bureau Report Retrieved", "Existing Liabilities Extracted", "Exception Flags Reviewed"] },
  { id: "cpv", code: "DEPT-07", name: "CPV / Verification", domain: "assess",
    purpose: "Verifies whether the information the applicant supplied is actually true and consistent.",
    receives: "CIB Team", handsTo: "Credit / Underwriting",
    human: "Field or phone agent conducts the actual verification and files findings.", system: "Tracks verification status: Verified, Partially Verified, Negative, Unable to Verify.",
    workflow: ["Verification Method Assigned", "Residence / Employment / Business Check", "Income Cross-Check", "Result Logged", "Routed to Credit"] },
  { id: "credit", code: "DEPT-08", name: "Credit / Underwriting", domain: "assess",
    purpose: "Determines creditworthiness and prepares a lending recommendation. The question shifts from 'is it complete' to 'should we lend.'",
    receives: "CPV / Verification", handsTo: "Credit Sanctioning Authority",
    human: "Analyst evaluates income, liabilities, stability, and risk; drafts a recommendation.", system: "Consolidates income, CIB, CPV, and policy rules into a risk score.",
    workflow: ["Consolidate All Inputs", "Assess Repayment Capacity", "Apply Credit Policy", "Risk Scoring", "Recommendation Drafted"] },
  { id: "sanctioning", code: "DEPT-09", name: "Credit Sanctioning Authority", domain: "assess",
    purpose: "Makes the final credit decision within its delegated approval authority — approve, refer, or decline.",
    receives: "Credit / Underwriting", handsTo: "Fulfillment",
    human: "Approving officer reviews the recommendation and signs off per delegated limits.", system: "Records the decision and approved terms against the application.",
    workflow: ["Review Recommendation", "Check Delegated Authority Limit", "Decide: Approve / Refer / Decline", "Set Approved Terms", "Record Sanction"] },
  { id: "fulfillment", code: "DEPT-10", name: "Fulfillment Team", domain: "fulfill",
    purpose: "Makes sure everything the approval requires is actually completed before the file can move to documentation.",
    receives: "Credit Sanctioning Authority", handsTo: "Documentation / Asset Operations",
    human: "Coordinates guarantor nomination, customer acknowledgement, and repayment account setup.", system: "Tracks each condition's status until all are marked complete.",
    workflow: ["Identify Required Conditions", "Guarantor Process (if required)", "Customer Acknowledgement", "Repayment Account Linked", "Conditions Marked Complete"] },
  { id: "docsops", code: "DEPT-11", name: "Documentation / Asset Operations", domain: "fulfill",
    purpose: "Ensures the approved facility is properly and completely documented, and operationally ready to disburse.",
    receives: "Fulfillment Team", handsTo: "Disbursement Team",
    human: "Checks document completeness, authenticity, and charges before sign-off.", system: "Generates document sets and tracks signature/upload status.",
    workflow: ["Document Set Generated", "Customer Signature", "Document Upload & Check", "Charges & Conditions Verified", "Marked Disbursement-Ready"] },
  { id: "legal", code: "DEPT-12", name: "Legal / Valuation / Security", domain: "fulfill",
    purpose: "Handles collateral, legal, and valuation requirements — only for products that require security (home, auto, cash-secured).",
    receives: "Documentation / Asset Operations", handsTo: "Documentation / Asset Operations",
    human: "Legal officer reviews title/ownership; valuer assesses the asset.", system: "Records valuation and security/lien creation against the facility.",
    workflow: ["Property / Vehicle Details Received", "Valuation Conducted", "Legal / Title Vetting", "Security / Lien Created"] },
  { id: "disbursement", code: "DEPT-13", name: "Disbursement Team", domain: "fulfill",
    purpose: "Performs the final check and releases the approved facility. The last operational gate before money moves.",
    receives: "Documentation / Asset Operations", handsTo: "Core Banking / CBS",
    human: "Authorizes the disbursement instruction per policy.", system: "Executes the fund transfer and triggers loan account creation.",
    workflow: ["Final Readiness Check", "Disbursement Instruction Raised", "Authorization", "Funds Released"] },
  { id: "corebanking", code: "DEPT-14", name: "Core Banking / CBS", domain: "use",
    purpose: "Creates and maintains the financial account and posts every transaction — the system of record for the whole bank.",
    receives: "Disbursement Team", handsTo: "Loan Servicing / Operations",
    human: "Operations monitors system health and reconciles exceptions.", system: "Posts every financial event: disbursement, interest, fees, transactions.",
    workflow: ["Event Received", "Validation", "Ledger Posting", "Balance & Statement Update"] },
  { id: "servicing", code: "DEPT-15", name: "Loan Servicing / Operations", domain: "use",
    purpose: "Maintains the loan or account after disbursement — EMI, interest, principal, statements, and customer requests.",
    receives: "Core Banking", handsTo: "Collection (if overdue) / Closure",
    human: "Handles servicing requests, rescheduling, and day-to-day maintenance.", system: "Runs the repayment schedule and posts each EMI.",
    workflow: ["EMI Schedule Generated", "EMI Due", "Payment Posted", "Statement Updated", "Next Cycle or Settlement"] },
  { id: "collection", code: "DEPT-16", name: "Collection", domain: "control",
    purpose: "Identifies and follows up on overdue repayments to bring the account back to current.",
    receives: "Loan Servicing", handsTo: "Recovery (if unresolved)",
    human: "Contacts the customer and negotiates a payment arrangement.", system: "Flags overdue accounts and tracks the collection workflow status.",
    workflow: ["Overdue Identified", "Customer Contacted", "Payment Follow-Up", "Arrangement Made or Escalated"] },
  { id: "recovery", code: "DEPT-17", name: "Recovery", domain: "control",
    purpose: "Manages seriously distressed or defaulted exposure — a different responsibility from routine collection.",
    receives: "Collection", handsTo: "Settlement / Closure",
    human: "Manages legal action, collateral enforcement, or restructuring.", system: "Tracks recovery status and eventual settlement outcome.",
    workflow: ["Case Escalated", "Legal / Collateral Review", "Recovery Action Selected", "Outcome Recorded"] },
  { id: "postreview", code: "DEPT-18", name: "Post-Disbursement Review / Control", domain: "control",
    purpose: "A second control layer that checks completed and disbursed files for compliance exceptions after the fact.",
    receives: "Core Banking / Disbursement", handsTo: "Risk / Compliance / Audit",
    human: "Reviews a sample or full set of disbursed files for policy adherence.", system: "Logs exceptions and tracks rectification.",
    workflow: ["File Selected for Review", "Control Check", "Exception Found?", "Rectification or Closure"] },
  { id: "custservice", code: "DEPT-19", name: "Customer Service", domain: "close",
    purpose: "Handles ongoing servicing requests and keeps the relationship alive after any single product closes.",
    receives: "Loan Servicing / any active product", handsTo: "Product Selection (new need)",
    human: "Resolves requests and complaints; identifies cross-sell opportunities.", system: "Logs and tracks service requests to resolution.",
    workflow: ["Request Logged", "Categorized & Routed", "Resolved", "Cross-Sell Opportunity Flagged"] },
  { id: "riskcompliance", code: "DEPT-20", name: "Risk / Compliance / Audit", domain: "control",
    purpose: "Provides control, monitoring, and regulatory oversight across the entire bank — a cross-cutting function, not a single point in the pipeline.",
    receives: "Every department (oversight)", handsTo: "Regulators / Senior Management",
    human: "Sets policy, reviews exceptions, and reports to regulators.", system: "Aggregates monitoring data across AML, credit, and transaction systems.",
    workflow: ["Policy Set", "Continuous Monitoring", "Exception Review", "Regulatory Reporting"] },
];

/* ================= MODULES (24) ================= */
export const CATS = [
  { id: "identity", label: "Identity & Compliance", color: "var(--c-know)" },
  { id: "deposit", label: "Deposit Products", color: "var(--c-sell)" },
  { id: "credit", label: "Credit & Lending", color: "var(--c-assess)" },
  { id: "cardspay", label: "Cards & Payments", color: "var(--c-use)" },
  { id: "ops", label: "Core & Risk Operations", color: "var(--c-control)" },
  { id: "retain", label: "Customer & Retention", color: "var(--c-close)" },
];
export const MODULES = [
  { id: "ekyc", code: "MOD-01", name: "eKYC", cat: "identity", dept: "sales",
    purpose: "Establishes who the applicant actually is, using NID and live face verification.",
    customer: "Provides NID, submits to a live face-verification capture.", bank: "Reviews exceptions and manual review queues when automated checks fail.",
    system: "Validates NID against issuing authority, matches face to ID photo, returns a pass/fail confidence score.",
    input: "NID number, applicant selfie/live capture.", output: "Verified identity record.", dependsOn: "National ID registry / biometric matching service.", usedBy: "KYC/CDD, CIF creation.",
    workflow: ["NID Capture", "OCR Data Extraction", "Registry Match", "Live Face Capture", "Face Match Score", "Verified / Manual Review"] },
  { id: "kyc", code: "MOD-02", name: "KYC / CDD", cat: "identity", dept: "riskcompliance",
    purpose: "Builds the customer due-diligence profile: occupation, source of funds, and risk category.",
    customer: "Declares personal, occupational, and financial background information.", bank: "Reviews declared information, assigns or confirms risk category.",
    system: "Stores the CDD profile and applies risk-scoring rules.", input: "Verified identity, declared customer information.", output: "KYC status and customer risk rating.",
    dependsOn: "eKYC.", usedBy: "CIF, AML screening, all product on-boarding.",
    workflow: ["Personal & Occupation Data", "Source-of-Funds Declaration", "Risk Category Rules Applied", "CDD Profile Created", "Enhanced Due Diligence If High-Risk"] },
  { id: "aml", code: "MOD-03", name: "AML / Sanctions Screening", cat: "identity", dept: "sanction",
    purpose: "Screens the customer and their transactions against sanctions and financial-crime watchlists.",
    customer: "No direct action — screening runs in the background.", bank: "Investigates and dispositions any alert raised by the screening engine.",
    system: "Matches customer/transaction data against watchlists and flags alerts.", input: "Customer profile, transaction data.", output: "Clear status or an alert requiring investigation.",
    dependsOn: "KYC/CDD, customer and transaction data.", usedBy: "CIF creation, account opening, loan disbursement, payments.",
    workflow: ["Watchlist Screening", "Name / Transaction Match", "Alert Generated (if any)", "Investigation", "Clear or Escalate"] },
  { id: "cif", code: "MOD-04", name: "CIF (Customer Information File)", cat: "identity", dept: "los",
    purpose: "Maintains one customer identity that every product — deposit, loan, or card — attaches to.",
    customer: "Nothing further required; the relationship is now established.", bank: "Owns the golden record for the customer; approves changes to core customer data.",
    system: "Creates and maintains the master customer record and unique customer ID.", input: "Verified, KYC-cleared, AML-cleared customer.", output: "CIF / unique customer ID.",
    dependsOn: "eKYC, KYC/CDD, AML.", usedBy: "All products: CASA, DPS, FDR, loans, cards.",
    workflow: ["Duplicate Customer Check", "Customer Data Consolidation", "CIF Number Generated", "Linked to Products"] },
  { id: "casa", code: "MOD-05", name: "CASA", cat: "deposit", dept: "servicing",
    purpose: "Opens and manages transactional savings or current accounts.",
    customer: "Requests the account, provides initial funding.", bank: "Approves account opening per product eligibility rules.",
    system: "Creates the account, assigns an account number, posts the initial deposit.", input: "Customer/CIF, product request.", output: "Active CASA account.",
    dependsOn: "CIF, KYC.", usedBy: "Cards, loan repayment accounts, all transactions.",
    workflow: ["Account Type Selection", "Eligibility Check", "Application", "Account Number Issued", "Initial Deposit", "Activation"] },
  { id: "dps", code: "MOD-06", name: "DPS", cat: "deposit", dept: "servicing",
    purpose: "Manages a recurring monthly savings commitment linked to a funding account.",
    customer: "Commits to a monthly installment; funds the account each cycle.", bank: "Monitors missed installments and applies the product's freeze/exception rules.",
    system: "Debits the linked account each cycle, tracks installment history and maturity.", input: "CIF, linked CASA account, product terms.", output: "Active DPS with running installment history.",
    dependsOn: "CIF, CASA.", usedBy: "Deposit servicing, potential collateral for secured lending.",
    workflow: ["Eligibility & Linked Account Check", "Tenure & Installment Selection", "DPS Opening", "Monthly Debit Cycle", "Missed-Installment Handling", "Maturity"] },
  { id: "fdr", code: "MOD-07", name: "FDR / Term Deposit", cat: "deposit", dept: "servicing",
    purpose: "Places customer funds for a fixed term at a fixed return.",
    customer: "Provides funds and selects a term.", bank: "Confirms placement terms and rate applicable at booking.",
    system: "Books the term deposit, accrues interest, manages maturity and renewal.", input: "CIF, source funds, selected term.", output: "Active FDR; at maturity, renewed or settled funds.",
    dependsOn: "CIF, CASA (source of funds).", usedBy: "Deposit servicing; can be pledged as security for a Cash-Secured Loan.",
    workflow: ["Source Fund Verification", "Term & Rate Selection", "FDR Booking", "Interest Accrual", "Maturity Decision: Renew / Settle"] },
  { id: "loanorig", code: "MOD-08", name: "Loan Origination", cat: "credit", dept: "los",
    purpose: "Captures and manages the loan application from product selection through submission.",
    customer: "Selects a loan product, supplies personal, business, and property information.", bank: "Reviews the application for completeness before it enters assessment.",
    system: "Stores application data as Draft, then Submitted, and routes it to assessment.", input: "CIF, product selection, applicant-supplied data.", output: "A complete, submitted loan application.",
    dependsOn: "CIF.", usedBy: "Income Assessment, CIB, Credit Assessment.",
    workflow: ["Product Selection", "Applicant Data Capture", "Business / Property Info (if applicable)", "Draft Saved", "Application Submitted"] },
  { id: "income", code: "MOD-09", name: "Income Assessment", cat: "credit", dept: "credit",
    purpose: "Determines the applicant's assessable income from all declared sources.",
    customer: "Declares salary/cash, rental, business/chamber, and other income.", bank: "Verifies declared income where required (documents, employer confirmation).",
    system: "Aggregates declared sources and calculates assessable income.", input: "Declared income sources from the application.", output: "Verified, assessable income figure.",
    dependsOn: "Loan Origination.", usedBy: "Credit Assessment.",
    workflow: ["Income Source Declaration", "Supporting Document Check", "Employer / Business Verification", "Income Aggregation", "Assessable Income Calculated"] },
  { id: "cib", code: "MOD-10", name: "CIB / Credit Bureau", cat: "credit", dept: "cib",
    purpose: "Determines the applicant's existing credit exposure and repayment history.",
    customer: "No direct action — bureau data is pulled using their identity.", bank: "Interprets bureau flags (e.g. classified accounts) per credit policy.",
    system: "Retrieves the credit bureau report and existing facility exposure.", input: "Applicant identity.", output: "Credit bureau report, existing obligations.",
    dependsOn: "Identity, Loan Origination.", usedBy: "Credit Assessment.",
    workflow: ["Applicant Bureau Pull", "Existing Facility Extraction", "Classification Check (SMA / Default)", "DBR Calculation", "Report Finalized"] },
  { id: "creditassess", code: "MOD-11", name: "Credit Assessment", cat: "credit", dept: "credit",
    purpose: "Assesses whether the applicant can reasonably service the requested facility.",
    customer: "No direct action beyond what's already been declared and verified.", bank: "Credit officer reviews the assessment output and applies judgement where policy allows.",
    system: "Combines income, CIB, existing exposure, and DBR into a risk profile and recommendation.", input: "Assessable income, CIB report, requested loan terms.", output: "A risk profile and lending recommendation.",
    dependsOn: "Income Assessment, CIB, Loan Origination.", usedBy: "Credit Decision.",
    workflow: ["Consolidate Income + CIB + Requested Terms", "Apply Credit Policy Rules", "Risk Scoring", "Recommendation Drafted", "Sent to Approving Authority"] },
  { id: "creditdecision", code: "MOD-12", name: "Credit Decision", cat: "credit", dept: "sanctioning",
    purpose: "Converts the assessment into an approve, decline, or refer outcome — and sets approved terms.",
    customer: "Is informed of the outcome; approved terms may differ from requested terms.", bank: "Approving authority signs off per delegated approval limits.",
    system: "Records the decision, approved amount, and tenure against the application.", input: "Credit assessment and recommendation.", output: "Approve / Decline / Refer, with approved terms if applicable.",
    dependsOn: "Credit Assessment.", usedBy: "Post-approval Conditions, Documentation, Disbursement.",
    workflow: ["Review Recommendation", "Apply Delegated Approval Authority", "Approve / Decline / Refer", "Set Approved Terms", "Record Decision"] },
  { id: "guarantor", code: "MOD-13", name: "Guarantor Management", cat: "credit", dept: "fulfillment",
    purpose: "Manages the guarantor obligation where the product or risk profile requires one.",
    customer: "Nominates a guarantor; the guarantor consents and is verified.", bank: "Confirms the guarantor meets policy requirements.",
    system: "Runs guarantor KYC and records acceptance against the loan.", input: "Guarantor identity and consent.", output: "Verified, accepted guarantor on file.",
    dependsOn: "Credit Decision (condition trigger).", usedBy: "Post-approval Conditions.",
    workflow: ["Guarantor Nomination", "Guarantor KYC", "Income / Liability Check", "Consent Signed", "Accepted on File"] },
  { id: "cpv", code: "MOD-14", name: "CPV / Digital Review Desk (DRD)", cat: "credit", dept: "drd", flagship: true,
    purpose: "Independently validates information supplied in the application — the digital review desk that cross-checks the file before it's allowed to proceed to fulfillment.",
    customer: "Makes themselves available for a field visit, a phone confirmation, or a digital verification prompt (e.g. a live location/photo check).",
    bank: "A DRD reviewer works the case queue, cross-checks documents against declared data, and files a verified/exception verdict against the file.",
    system: "Routes the case to the queue, timestamps every checkpoint, tracks status (Queued — In Progress — Verified/Exception), and pushes the verdict back into Loan Origination.",
    input: "Submitted application data, uploaded documents, contact details requiring independent validation.", output: "A verified or exception verdict, with findings logged against the application.",
    dependsOn: "Loan Origination (submitted application), Documentation (uploaded documents).",
    usedBy: "Post-approval Conditions, Final Verification, Credit Decision (exceptions can trigger re-assessment).",
    workflow: ["Case Queued to DRD", "Document Cross-Check", "Verification Method Assigned", "Contact / Field / Digital Check Conducted", "Findings Logged", "Verdict: Verified or Exception", "Routed Back to Origination"],
    workflowDesc: [
      "The submitted file lands in the DRD queue the moment the application is complete — before it can move any further.",
      "A reviewer checks the uploaded documents against what the applicant declared: does the address match, does the income document match the stated employer, does the signature match?",
      "Based on the product and risk level, the case is assigned a verification method — a phone confirmation, a field visit, or a digital check like a live photo/location capture.",
      "The actual check happens: a call is made, a visit occurs, or the applicant completes a digital prompt in real time.",
      "Whatever is found — confirmed, mismatched, unreachable, suspicious — is logged against the file with a timestamp and reviewer ID.",
      "The desk closes the case with a verdict: Verified lets the file continue; Exception flags it for review or correction.",
      "The verdict is pushed back to Loan Origination, which either continues fulfillment or halts for correction/reassessment.",
    ] },
  { id: "docs", code: "MOD-15", name: "Documentation", cat: "credit", dept: "docsops",
    purpose: "Generates, collects, and validates the legal documents for an approved facility.",
    customer: "Reviews and signs the loan documents; uploads required paperwork.", bank: "Verifies document completeness and authenticity before disbursement.",
    system: "Generates document sets, tracks signature and upload status.", input: "Approved facility terms.", output: "Signed, verified loan documentation.",
    dependsOn: "Credit Decision.", usedBy: "Disbursement.",
    workflow: ["Document Set Generated", "Customer Review", "Signature", "Document Upload", "Authenticity Check", "Filed"] },
  { id: "repayacct", code: "MOD-16", name: "Repayment Account", cat: "credit", dept: "fulfillment",
    purpose: "Establishes the account from which scheduled repayments will be collected.",
    customer: "Nominates or confirms a CASA account for EMI collection.", bank: "Confirms the account is valid and belongs to the borrower (or approved payer).",
    system: "Links the loan facility to the CASA account for scheduled debits.", input: "Borrower's CASA account.", output: "A linked repayment account on the loan facility.",
    dependsOn: "CASA.", usedBy: "Disbursement, ongoing loan servicing.",
    workflow: ["Nominate CASA", "Ownership Match Check", "Link to Loan Facility", "EMI Debit Mandate Setup"] },
  { id: "disbursement", code: "MOD-17", name: "Disbursement", cat: "credit", dept: "disbursement",
    purpose: "Releases approved funds once every condition, document, and verification is complete.",
    customer: "Receives the disbursed funds into the nominated account.", bank: "Authorizes the disbursement instruction per policy.",
    system: "Executes the fund transfer and creates the active loan account in core banking.", input: "Completed conditions, documents, and final verification.", output: "Disbursed funds; an active loan account.",
    dependsOn: "Documentation, Repayment Account, CPV, Guarantor (where applicable).", usedBy: "Core Banking, loan servicing.",
    workflow: ["Condition Completion Check", "Disbursement Instruction Raised", "Authorization", "Funds Transfer Executed", "Loan Account Activated"] },
  { id: "cards", code: "MOD-18", name: "Cards", cat: "cardspay", dept: "servicing",
    purpose: "Issues and manages debit and credit cards.",
    customer: "Applies for a card, activates it, and uses it for spend/withdrawal.", bank: "Approves issuance (credit cards also route through Credit Assessment).",
    system: "Issues the physical/virtual card, sets limits, processes activation.", input: "CIF (debit) or CIF + credit assessment (credit).", output: "Active, usable card.",
    dependsOn: "CIF, CASA (debit) or Credit Assessment (credit).", usedBy: "Payment processing, customer daily use.",
    workflow: ["Card Type Selection", "Eligibility / Credit Check (if credit)", "Personalization / Printing", "Dispatch", "Activation", "PIN Set"] },
  { id: "payment", code: "MOD-19", name: "Payment Processing", cat: "cardspay", dept: "corebanking",
    purpose: "Executes and settles financial transactions across all channels.",
    customer: "Initiates a transfer, bill payment, merchant payment, or withdrawal.", bank: "Investigates flagged or failed transactions.",
    system: "Authenticates, validates limits/balance, screens for fraud, posts, and settles the transaction.", input: "Payment instruction from an active account or card.", output: "Posted, settled transaction with notification.",
    dependsOn: "CASA / Cards, Core Banking.", usedBy: "Customer, reconciliation, reporting.",
    workflow: ["Instruction Initiated", "Authentication (PIN / OTP)", "Balance / Limit Check", "Fraud Screening", "Processing", "Posting & Settlement", "Notification"] },
  { id: "corebanking", code: "MOD-20", name: "Core Banking / Ledger", cat: "ops", dept: "corebanking",
    purpose: "Maintains the single source of truth for all accounts, balances, and postings.",
    customer: "No direct action — this runs behind every product a customer holds.", bank: "Operations teams monitor system health and reconcile exceptions.",
    system: "Posts every financial event: deposits, loans, interest, fees, transactions.", input: "Every financial event across all products.", output: "Accurate balances, statements, and the system of record.",
    dependsOn: "All product-origination modules.", usedBy: "Everything — servicing, reporting, closure.",
    workflow: ["Event Received", "Validation", "Ledger Posting", "Balance Update", "Interest / Fee Accrual", "Statement Update"] },
  { id: "collection", code: "MOD-21", name: "Collection", cat: "ops", dept: "collection",
    purpose: "Manages accounts that have missed a scheduled repayment.",
    customer: "Is contacted and, where possible, arranges payment.", bank: "Collections officer follows the escalation path defined by policy.",
    system: "Flags overdue accounts and tracks the collection workflow status.", input: "An overdue EMI or payment.", output: "Payment recovered, or escalation to Recovery.",
    dependsOn: "Core Banking (overdue detection).", usedBy: "Recovery, Settlement.",
    workflow: ["Overdue Flag Raised", "Customer Notification", "Contact Attempt", "Payment Arrangement", "Escalation Decision"] },
  { id: "recovery", code: "MOD-22", name: "Recovery", cat: "ops", dept: "recovery",
    purpose: "Resolves accounts that have moved into serious delinquency or default.",
    customer: "Engages in a resolution — restructuring, settlement, or collateral action.", bank: "Recovery team manages the legal/collateral process per policy.",
    system: "Tracks recovery status and the eventual settlement outcome.", input: "An account escalated from Collection.", output: "Settled exposure or realized collateral.",
    dependsOn: "Collection, collateral records (FDR/property/vehicle).", usedBy: "Settlement, Closure.",
    workflow: ["Case Escalated", "Legal / Collateral Review", "Recovery Action Selected", "Settlement Negotiated", "Outcome Recorded"] },
  { id: "custservice", code: "MOD-23", name: "Customer Service", cat: "retain", dept: "custservice",
    purpose: "Handles ongoing servicing requests and retains the relationship after any single product closes.",
    customer: "Raises requests, complaints, or expresses interest in new products.", bank: "Resolves requests and identifies cross-sell opportunities.",
    system: "Logs and tracks service requests to resolution.", input: "Customer requests, complaints, servicing needs.", output: "Resolved requests; new product leads.",
    dependsOn: "CIF, all active products.", usedBy: "Product Selection (new product loop).",
    workflow: ["Request Logged", "Categorized & Routed", "Resolved", "Cross-Sell Opportunity Flagged"] },
  { id: "reporting", code: "MOD-24", name: "Reporting & Reconciliation", cat: "ops", dept: "postreview",
    purpose: "Ensures the business and financial position is correct and reportable.",
    customer: "No direct action.", bank: "Finance/operations review reports and resolve reconciliation breaks.",
    system: "Aggregates core banking data into regulatory and management reports.", input: "Transactions and postings from Core Banking.", output: "Reconciled, reportable financial and business data.",
    dependsOn: "Core Banking.", usedBy: "Regulatory reporting, management, audit.",
    workflow: ["Data Extraction from Core Banking", "Reconciliation Check", "Exception Investigation", "Regulatory Report Compiled", "Submitted / Filed"] },
];

export const CAT_COLOR = {};
CATS.forEach((c) => { CAT_COLOR[c.id] = c.color; });
export const MOD_BY_ID = {};
MODULES.forEach((m) => { MOD_BY_ID[m.id] = m; });
export const DEPT_BY_ID = {};
DEPARTMENTS.forEach((d) => { DEPT_BY_ID[d.id] = d; });

/* ================= LIVE DEPARTMENT HANDOFF MAP ================= */
export const FLOW_NODES = [
  { id: "customer", label: "Customer", col: 0, row: 1 },
  { id: "sales", label: "Sales / RM", col: 1, row: 1 },
  { id: "los", label: "LOS", col: 2, row: 1 },
  { id: "drd", label: "DRD", col: 3, row: 1 },
  { id: "dedupe", label: "Dedupe", col: 4, row: 1 },
  { id: "sanction", label: "Sanction Screen", col: 5, row: 1 },
  { id: "cib", label: "CIB", col: 6, row: 1 },
  { id: "cpv", label: "CPV", col: 7, row: 1 },
  { id: "credit", label: "Credit / Underwriting", col: 8, row: 1 },
  { id: "sanctioning", label: "Sanctioning Authority", col: 9, row: 1 },
  { id: "declined", label: "Declined — Closed", col: 9, row: 0, terminal: true },
  { id: "fulfillment", label: "Fulfillment", col: 10, row: 1 },
  { id: "docsops", label: "Documentation", col: 11, row: 1 },
  { id: "disbursement", label: "Disbursement", col: 12, row: 1 },
  { id: "corebanking", label: "Core Banking", col: 13, row: 1 },
  { id: "servicing", label: "Loan Servicing", col: 14, row: 1 },
  { id: "collection", label: "Collection", col: 14, row: 2 },
  { id: "recovery", label: "Recovery", col: 14, row: 3 },
  { id: "closure", label: "Closure", col: 15, row: 1 },
];
export const COLW = 168;
export const ROWY = { 0: 50, 1: 170, 2: 290, 3: 410 };
export function nodeXY(id) {
  const n = FLOW_NODES.find((x) => x.id === id);
  return { x: n.col * COLW + 90, y: ROWY[n.row] };
}
export const FLOW_EDGES = [
  { from: "customer", to: "sales", type: "main" },
  { from: "sales", to: "los", type: "main" },
  { from: "los", to: "drd", type: "main" },
  { from: "drd", to: "dedupe", type: "main" },
  { from: "dedupe", to: "sanction", type: "main" },
  { from: "sanction", to: "cib", type: "main" },
  { from: "cib", to: "cpv", type: "main" },
  { from: "cpv", to: "credit", type: "main" },
  { from: "credit", to: "sanctioning", type: "main" },
  { from: "sanctioning", to: "fulfillment", type: "main" },
  { from: "fulfillment", to: "docsops", type: "main" },
  { from: "docsops", to: "disbursement", type: "main" },
  { from: "disbursement", to: "corebanking", type: "main" },
  { from: "corebanking", to: "servicing", type: "main" },
  { from: "servicing", to: "closure", type: "main" },
  { from: "servicing", to: "collection", type: "main" },
  { from: "collection", to: "recovery", type: "main" },
  { from: "recovery", to: "closure", type: "main" },
  { from: "drd", to: "sales", type: "feedback", bow: "down" },
  { from: "cpv", to: "sales", type: "feedback", bow: "down" },
  { from: "sanctioning", to: "declined", type: "feedback", bow: "up" },
  { from: "collection", to: "servicing", type: "feedback", bow: "side" },
];
export function edgePathD(e) {
  const a = nodeXY(e.from), b = nodeXY(e.to);
  if (e.type === "main") { return `M${a.x},${a.y} L${b.x},${b.y}`; }
  if (e.bow === "down") {
    const midY = Math.max(a.y, b.y) + 70;
    return `M${a.x},${a.y + 16} C${a.x},${midY} ${b.x},${midY} ${b.x},${b.y + 16}`;
  }
  if (e.bow === "up") {
    const midY = Math.min(a.y, b.y) - 40;
    return `M${a.x},${a.y - 16} C${a.x},${midY} ${b.x},${midY} ${b.x},${b.y + 16}`;
  }
  const midX = Math.max(a.x, b.x) + 46;
  return `M${a.x + 16},${a.y} C${midX},${a.y} ${midX},${b.y} ${b.x + 16},${b.y}`;
}

/* ---- Scenarios ---- */
export const SCENARIOS = [
  { id: 'clean', label: 'Scenario A — Straight-Through Approval', steps: [
    { node: "customer", note: "Customer expresses a loan need." },
    { node: "sales", note: "Sales/RM captures details and creates the application." },
    { node: "los", note: "Application is parked in LOS with an Application ID." },
    { node: "drd", note: "DRD reviews completeness — Complete." },
    { node: "dedupe", note: "Dedupe confirms no duplicate customer or application." },
    { node: "sanction", note: "Sanction/AML screening — Clear." },
    { node: "cib", note: "CIB report retrieved — acceptable exposure." },
    { node: "cpv", note: "CPV verification — Verified." },
    { node: "credit", note: "Credit assessment completed — recommended for approval." },
    { node: "sanctioning", note: "Sanctioning authority — Approved." },
    { node: "fulfillment", note: "Conditions fulfilled — guarantor, acknowledgement, repayment account." },
    { node: "docsops", note: "Documentation signed, uploaded, and checked." },
    { node: "disbursement", note: "Final check passed — funds disbursed." },
    { node: "corebanking", note: "Loan account booked in core banking." },
    { node: "servicing", note: "Loan is active — EMIs proceeding normally." },
    { node: "closure", note: "Loan fully settled and closed." },
  ] },
  { id: 'drd-return', label: 'Scenario B — Returned for Correction at DRD', steps: [
    { node: "customer", note: "Customer submits an application with an unclear document photo." },
    { node: "sales", note: "Sales/RM submits the application as-is." },
    { node: "los", note: "Application parked in LOS." },
    { node: "drd", note: "DRD finds a Deficiency — document unreadable.", feedback: true },
    { node: "sales", note: "Returned to Sales/RM for correction.", feedbackHop: true },
    { node: "los", note: "Corrected application resubmitted to LOS." },
    { node: "drd", note: "DRD reviews again — now Complete." },
    { node: "dedupe", note: "Dedupe — no duplicates found." },
    { node: "sanction", note: "Sanction/AML screening — Clear." },
    { node: "cib", note: "CIB retrieved — acceptable." },
    { node: "cpv", note: "CPV — Verified." },
    { node: "credit", note: "Credit assessment — recommended." },
    { node: "sanctioning", note: "Approved." },
    { node: "fulfillment", note: "Conditions fulfilled." },
    { node: "docsops", note: "Documentation complete." },
    { node: "disbursement", note: "Disbursed." },
    { node: "corebanking", note: "Booked in core banking." },
    { node: "servicing", note: "Active loan, servicing normally." },
    { node: "closure", note: "Settled and closed." },
  ] },
  { id: 'cpv-negative', label: 'Scenario C — CPV Exception, Re-Verified', steps: [
    { node: "customer", note: "Applicant declares an office address that turns out to be outdated." },
    { node: "sales", note: "Application submitted." },
    { node: "los", note: "Parked in LOS." },
    { node: "drd", note: "DRD — Complete." },
    { node: "dedupe", note: "No duplicates." },
    { node: "sanction", note: "Screening clear." },
    { node: "cib", note: "CIB acceptable." },
    { node: "cpv", note: "CPV — Negative, office address could not be confirmed.", feedback: true },
    { node: "sales", note: "Sent back to Sales/RM to obtain updated employment details.", feedbackHop: true },
    { node: "los", note: "Updated details resubmitted." },
    { node: "drd", note: "DRD re-checks — Complete." },
    { node: "dedupe", note: "Still no duplicates." },
    { node: "sanction", note: "Still clear." },
    { node: "cib", note: "CIB unaffected." },
    { node: "cpv", note: "CPV re-attempted — now Verified." },
    { node: "credit", note: "Credit assessment proceeds." },
    { node: "sanctioning", note: "Approved." },
    { node: "fulfillment", note: "Conditions fulfilled." },
    { node: "docsops", note: "Documentation complete." },
    { node: "disbursement", note: "Disbursed." },
    { node: "corebanking", note: "Booked." },
    { node: "servicing", note: "Active and current." },
    { node: "closure", note: "Closed." },
  ] },
  { id: 'declined', label: 'Scenario D — Declined at Sanction', steps: [
    { node: "customer", note: "Applicant requests a loan beyond their repayment capacity." },
    { node: "sales", note: "Application submitted." },
    { node: "los", note: "Parked." },
    { node: "drd", note: "Complete." },
    { node: "dedupe", note: "No duplicates." },
    { node: "sanction", note: "Clear." },
    { node: "cib", note: "High existing exposure found." },
    { node: "cpv", note: "Verified." },
    { node: "credit", note: "Assessment shows repayment capacity is insufficient." },
    { node: "sanctioning", note: "Decision: Declined.", feedback: true },
    { node: "declined", note: "Customer is notified. Application closed — no further processing.", feedbackHop: true },
  ] },
  { id: 'overdue', label: 'Scenario E — Overdue — Regularized', steps: [
    { node: "corebanking", note: "Loan is active in core banking." },
    { node: "servicing", note: "EMI falls due." },
    { node: "collection", note: "EMI missed — flagged Overdue. Collection contacts the customer.", feedback: true },
    { node: "servicing", note: "Customer pays and regularizes — back to normal servicing.", feedbackHop: true },
  ] },
  { id: 'recovery', label: 'Scenario F — Escalated to Recovery', steps: [
    { node: "corebanking", note: "Loan is active." },
    { node: "servicing", note: "EMI falls due." },
    { node: "collection", note: "Missed EMI — Collection follow-up begins." },
    { node: "recovery", note: "Delinquency continues — escalated to Recovery." },
    { node: "closure", note: "Collateral realized / settlement reached — case closed." },
  ] },
];
